"""empty message

Revision ID: 31534806a3cf
Revises: f5ac3ece5358
Create Date: 2023-06-08 11:21:01.696567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31534806a3cf'
down_revision = 'f5ac3ece5358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas_ampu',
    sa.Column('kode_kelas', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['kode_kelas'], ['kelas.kode_kelas'], ),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], ),
    sa.PrimaryKeyConstraint('kode_kelas', 'nim')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelas_ampu')
    # ### end Alembic commands ###
