"""empty message

Revision ID: 5deca127ed35
Revises: 
Create Date: 2023-06-07 13:49:00.159378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5deca127ed35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nip'])

    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.alter_column('nip',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('kode_mk',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('kelas_ampu', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nim', type_='foreignkey')
        batch_op.drop_constraint('fk_kode_kelas', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mahasiswa', ['nim'], ['nim'])
        batch_op.create_foreign_key(None, 'kelas', ['kode_kelas'], ['kode_kelas'])

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.alter_column('gender_mhs',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['nim'])

    with op.batch_alter_table('mata_kuliah', schema=None) as batch_op:
        batch_op.drop_constraint('mata_kuliah_nama_mk_key', type_='unique')
        batch_op.create_unique_constraint(None, ['kode_mk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mata_kuliah', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('mata_kuliah_nama_mk_key', ['nama_mk'])

    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('gender_mhs',
               existing_type=sa.String(),
               type_=sa.CHAR(length=1),
               existing_nullable=False)

    with op.batch_alter_table('kelas_ampu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_kode_kelas', 'kelas', ['kode_kelas'], ['kode_kelas'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_nim', 'mahasiswa', ['nim'], ['nim'], ondelete='CASCADE')

    with op.batch_alter_table('kelas', schema=None) as batch_op:
        batch_op.alter_column('kode_mk',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nip',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
