"""relationship list_kelas

Revision ID: f5ac3ece5358
Revises: 5deca127ed35
Create Date: 2023-06-08 10:46:13.589845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ac3ece5358'
down_revision = '5deca127ed35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelas_ampu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas_ampu',
    sa.Column('nim', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kode_kelas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['kode_kelas'], ['kelas.kode_kelas'], name='kelas_ampu_kode_kelas_fkey'),
    sa.ForeignKeyConstraint(['nim'], ['mahasiswa.nim'], name='kelas_ampu_nim_fkey'),
    sa.PrimaryKeyConstraint('nim', 'kode_kelas', name='kelas_ampu_pkey')
    )
    # ### end Alembic commands ###
